/** Placeholder values shown in the designer preview — never real student/staff data. Mirrors src/features/id-cards/sample-card-data.ts. */
export const SAMPLE_CERTIFICATE_DATA: Record<string, string> = {
  "school.name": "Greenwood Public School",
  "school.address": "123 MG Road, Pune, Maharashtra",
  "school.principalName": "Dr. Anita Rao",
  "school.udisePlusCode": "27140100123",
  "school.affiliationBoard": "CBSE",
  "certificate.number": "TC/2026/00045",
  "certificate.issueDate": "26 Aug 2026",
  "student.name": "Aarav Sharma",
  "student.admissionNumber": "ADM1024",
  "student.class": "10",
  "student.section": "A",
  "student.rollNumber": "12",
  "student.dateOfBirth": "14 Mar 2011",
  "student.gender": "Male",
  "student.guardianName": "Rajesh Sharma",
  "student.address": "45 Lake View Colony, Pune",
  "student.admissionDate": "05 Jun 2020",
  "student.previousSchool": "Sunrise Academy",
  "academicYear.label": "2026-27",
  "staff.name": "Priya Verma",
  "staff.employeeId": "EMP-0042",
  "staff.designation": "PGT Physics",
  "staff.department": "Science",
  "staff.joiningDate": "01 Jun 2019",
  "staff.dateOfBirth": "22 Jul 1988",
  "staff.address": "12 Church Road, Pune",
};
